---
- name: ensure dependency packages present
  yum:
    name:
      - 'libuuid-devel'
      - 'libtool'
      - 'pkgconfig'
      - 'autoconf'
      - 'automake'
      - 'gcc'
      - 'gcc-c++'
      - 'make'
    state: present

- name: install libsodium-devel for zeromq new version
  yum:
    name: 'libsodium-devel'
    state: present
  when: zeromq_version != '4.0.5'

- name: download libzmq source
  get_url:
    url: '{{ zeromq_download_url }}'
    dest: '/tmp/zeromq-{{ zeromq_version }}.tar.gz'
    validate_certs: no

- name: unarchive libzmq source
  unarchive:
    src: '/tmp/zeromq-{{ zeromq_version }}.tar.gz'
    dest: '/tmp/'
    copy: no
  args:
    creates: '/tmp/zeromq-{{ zeromq_version }}'

- name: install libzmq from source
  shell: './configure && make && make install'
  args:
    chdir: '/tmp/zeromq-{{ zeromq_version }}'
    creates: '/usr/local/lib/libzmq.so'
