# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.ssh.forward_agent = true
  config.ssh.host = 'localhost'
  config.ssh.port = '2260'
  config.ssh.private_key_path = '~/.vagrant.d/insecure_private_key'

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :docker do |docker|
    docker.image = 'juwaicom/amazonlinux-vagrant:2.0'
    docker.force_host_vm = false
    docker.has_ssh = true
    docker.ports = [
        '2260:22',
    ]
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.verbose = 'v'
    ansible.playbook = 'test.yml'
  end
end
